### ISSUE TITLE
how to config with a etcd?

### ISSUE THREAD

**Issue by culiangfanzi** [AdoHe/dashboard#1]
I have already opened the localhost:port/mod/dashboard/browser, but how can I use it with my etcd,which has a version of 2.2.0?

**Comment by adohe-zz** [comment]
@culiangfanzi I am afraid you have to modify the `app.js` file to config your etcd endpoint. In fact, there is a `getHost` function within `app.js` , by default it returns `http://127.0.0.1:4001`, you can change this to an appropriate etcd endpoint.
